### python原生函数计算速度与numpy计算速度比较

In [27]:
import random
import time
import numpy as np

# 生成一个大数组
python_list = []

for i in range(100000000):
    python_list.append(random.random())
    #随机生成一亿个数字，并添加到列表中，传统方法
    
ndarray_list = np.array(python_list)    # 储存时已经是新方法了，数据与数据的地址都是连续的 
len(ndarray_list)    # 可以显示有一亿长度

# 原生pythonlist求和
t1 = time.time()    # 记录下初始时间t1
a= sum(python_list)
t2 = time.time()    # 记录下添加完列表后的时间t2
d1 = t2 - t1    # 相减后得出计算时间d1

# ndarray求和
t3 = time.time()
b = np.sum(ndarray_list)
t4 = time.time()
d2 = t4 - t3    # 相减后得出计算时间d2



In [25]:
d1

0.571476936340332

In [29]:
d2

0.11070418357849121

### ndarray的属性

In [ ]:
import numpy as np
score = np.array([[80, 89, 86, 67, 79],
                [78, 97, 89, 67 ,81],
                [90, 94, 78, 67, 74],
                [91, 91, 90, 67, 69],
                [76, 87, 75, 67, 86],
                [70, 79, 84, 67, 84],
                [94, 92, 93, 67, 64],
                [86, 85, 83, 67, 80]])

score.shape    # (8， 5) 8行5列

score.ndim    # dim= dimension 维度

score.size    # 总共元素

score.dtype    # 类型  没有指定类型，整数 int32

score.itemsize    # 4个字节  int32 4个字节
 


4

### ndarray的形状

In [45]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2, 3, 4])
c = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [38]:
a    # (2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
b    # (4, )

array([1, 2, 3, 4])

In [46]:
c    # (2, 2, 3)  三维数组，第一个2是指两个二维数组嵌套

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [47]:
a.shape

(2, 3)

In [48]:
b.shape

(4,)

In [49]:
c.shape

(2, 2, 3)

### ndarray的类型

In [52]:
data = np.array([1.1, 2.2, 3.3])

In [57]:
data.dtype    # float64

dtype('float64')

In [58]:
# 创建数组时指定类型
np.array([1.1, 2.2, 3.3], dtype="float32")

array([1.1, 2.2, 3.3], dtype=float32)

In [60]:
np.array([1.1, 2.2, 3.3], dtype=np.float32)

array([1.1, 2.2, 3.3], dtype=float32)