In [4]:
import numpy as np
stock_change = np.random.normal(loc=0, scale=1, size=(8, 10)) 
stock_change[stock_change > 0.5] = 1.1

In [6]:
stock_change

array([[ 1.1       ,  0.28520023,  1.1       , -0.50130067,  1.1       ,
         0.15788752, -0.31097313, -0.92697568, -0.23714903,  1.1       ],
       [ 1.1       , -0.6976564 , -1.57465049, -1.39945863,  0.46014845,
        -0.02636874,  1.1       ,  0.28649177,  1.1       , -1.10445816],
       [ 1.1       ,  0.21877993, -1.31172162,  1.1       , -0.72966108,
        -1.40265672,  0.25204688,  1.1       ,  0.07498743, -1.41100713],
       [ 1.1       , -0.62903975,  0.2464008 ,  1.1       , -1.26872408,
        -1.10699607,  0.07327727,  0.23669136, -0.68436541,  1.1       ],
       [ 0.47374118,  1.1       ,  0.1950066 , -0.22119788, -1.47804791,
         1.1       ,  1.1       , -0.13801895, -0.90477722, -0.5338313 ],
       [-1.59768256, -1.86372032, -1.79653706,  0.42386101,  0.11971698,
        -0.57010681,  0.31868359,  1.1       ,  0.28181078, -1.10223519],
       [ 1.1       , -0.83565651, -0.75776969, -0.01765257,  1.1       ,
        -0.21422038,  1.1       , -0.83561949

### 合并

In [8]:
a = stock_change[:2, 0:4]
b = stock_change[4:6, 0:4]

In [9]:
a

array([[ 1.1       ,  0.28520023,  1.1       , -0.50130067],
       [ 1.1       , -0.6976564 , -1.57465049, -1.39945863]])

In [10]:
b

array([[ 0.47374118,  1.1       ,  0.1950066 , -0.22119788],
       [-1.59768256, -1.86372032, -1.79653706,  0.42386101]])

In [12]:
np.hstack((a, b))    # 水平拼接

array([[ 1.1       ,  0.28520023,  1.1       , -0.50130067,  0.47374118,
         1.1       ,  0.1950066 , -0.22119788],
       [ 1.1       , -0.6976564 , -1.57465049, -1.39945863, -1.59768256,
        -1.86372032, -1.79653706,  0.42386101]])

In [13]:
# https://www.cnblogs.com/shueixue/p/10953699.html  concatenate函数用法
np.concatenate((a, b), axis=1)    # 与上面结果相同

array([[ 1.1       ,  0.28520023,  1.1       , -0.50130067,  0.47374118,
         1.1       ,  0.1950066 , -0.22119788],
       [ 1.1       , -0.6976564 , -1.57465049, -1.39945863, -1.59768256,
        -1.86372032, -1.79653706,  0.42386101]])

In [15]:
np.vstack((a, b))    # 竖直拼接

array([[ 1.1       ,  0.28520023,  1.1       , -0.50130067],
       [ 1.1       , -0.6976564 , -1.57465049, -1.39945863],
       [ 0.47374118,  1.1       ,  0.1950066 , -0.22119788],
       [-1.59768256, -1.86372032, -1.79653706,  0.42386101]])

In [16]:
np.concatenate((a, b), axis=0)    # 与上面结果相同

array([[ 1.1       ,  0.28520023,  1.1       , -0.50130067],
       [ 1.1       , -0.6976564 , -1.57465049, -1.39945863],
       [ 0.47374118,  1.1       ,  0.1950066 , -0.22119788],
       [-1.59768256, -1.86372032, -1.79653706,  0.42386101]])

In [19]:
# 分割示例
x = np.arange(9)
np.split(x, 3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [22]:
y = np.arange(9)
np.split(y, [3, 5, 6, 10])

[array([0, 1, 2]),
 array([3, 4]),
 array([5]),
 array([6, 7, 8]),
 array([], dtype=int32)]

### IO操作与数据处理

In [2]:
import numpy as np
data = np.genfromtxt("test.csv", delimiter=",")
# 从本地读取一个test.csv文件中的内容

In [6]:
data    #中文和空缺地方会出现nan，表示缺少数据，如果想要处理十分麻烦，但用pandas会变得很简单


array([[  nan,   nan,   nan,   nan],
       [  1. , 123. ,   1.4,  23. ],
       [  2. , 110. ,   nan,  18. ],
       [  3. ,   nan,   2.1,  19. ]])

numpy.ndarray