In [17]:
import numpy as np
stock_change = np.random.normal(loc=0, scale=1, size=(8, 10))    # 8是8个列表股票， 10是10天, 生成的是一个二维数组

In [32]:
stock_change

array([[ 0.26625673,  0.22626729,  0.33018776, -0.77039285,  1.1       ,
         1.1       , -0.28298564, -0.73305017, -1.0002275 , -0.4176792 ],
       [ 1.1       ,  1.1       ,  1.1       ,  0.2987972 ,  1.1       ,
        -0.26171509, -0.5312818 ,  0.29954042, -0.29697824,  1.1       ],
       [-0.73858731, -0.55980198, -0.58424396, -0.81942324, -1.24105187,
        -1.24203236, -1.11057786,  0.38941405,  0.26492695, -0.84461079],
       [ 0.03093299, -1.57553085, -1.24742813,  1.1       , -0.94105419,
        -1.1550871 ,  1.1       ,  1.1       ,  0.2551404 , -0.35682679],
       [-0.07707965,  0.30550267, -0.30174488,  1.1       , -1.61949707,
        -1.34063498,  1.1       , -0.8818434 ,  0.33481671, -0.02777665],
       [ 1.1       , -1.14752339, -1.81857403, -0.2684595 ,  1.1       ,
        -2.04854849,  0.08446703, -0.78567684,  1.1       ,  0.27680066],
       [ 0.00878591,  1.1       ,  0.34407525,  1.1       ,  0.31835269,
         0.15578901, -0.35917903,  1.1       

In [33]:
# 逻辑判断，如果涨跌幅大于0.5就标记为True 否则为False
stock_change > 0,5

(array([[ True,  True,  True, False,  True,  True, False, False, False,
         False],
        [ True,  True,  True,  True,  True, False, False,  True, False,
          True],
        [False, False, False, False, False, False, False,  True,  True,
         False],
        [ True, False, False,  True, False, False,  True,  True,  True,
         False],
        [False,  True, False,  True, False, False,  True, False,  True,
         False],
        [ True, False, False, False,  True, False,  True, False,  True,
          True],
        [ True,  True,  True,  True,  True,  True, False,  True, False,
         False],
        [ True, False, False,  True, False,  True,  True, False,  True,
          True]]),
 5)

In [34]:
stock_change[stock_change > 0.5] = 1.1   # 筛选出> 0.5的数据 

In [35]:
stock_change

array([[ 0.26625673,  0.22626729,  0.33018776, -0.77039285,  1.1       ,
         1.1       , -0.28298564, -0.73305017, -1.0002275 , -0.4176792 ],
       [ 1.1       ,  1.1       ,  1.1       ,  0.2987972 ,  1.1       ,
        -0.26171509, -0.5312818 ,  0.29954042, -0.29697824,  1.1       ],
       [-0.73858731, -0.55980198, -0.58424396, -0.81942324, -1.24105187,
        -1.24203236, -1.11057786,  0.38941405,  0.26492695, -0.84461079],
       [ 0.03093299, -1.57553085, -1.24742813,  1.1       , -0.94105419,
        -1.1550871 ,  1.1       ,  1.1       ,  0.2551404 , -0.35682679],
       [-0.07707965,  0.30550267, -0.30174488,  1.1       , -1.61949707,
        -1.34063498,  1.1       , -0.8818434 ,  0.33481671, -0.02777665],
       [ 1.1       , -1.14752339, -1.81857403, -0.2684595 ,  1.1       ,
        -2.04854849,  0.08446703, -0.78567684,  1.1       ,  0.27680066],
       [ 0.00878591,  1.1       ,  0.34407525,  1.1       ,  0.31835269,
         0.15578901, -0.35917903,  1.1       

### 通用判断函数

In [38]:
# 判断stock_change[0:2, 0:5]是否全是上涨的
stock_change[0:2, 0:5]    
# 我也不知道为什么取出了第一个数组的前5个和第二个数组的前5个 应该是左闭右开吧
# 二维数组，省略了步长

array([[ 0.26625673,  0.22626729,  0.33018776, -0.77039285,  1.1       ],
       [ 1.1       ,  1.1       ,  1.1       ,  0.2987972 ,  1.1       ]])

In [39]:
stock_change[0:2, 0:5] > 0

array([[ True,  True,  True, False,  True],
       [ True,  True,  True,  True,  True]])

In [40]:
np.all(stock_change[0:2, 0:5] > 0)    # np.all需要全部为True才能输出True

False

In [41]:
### 判断前5只股票这段期间是否任意一只有上涨
np.any(stock_change[0:5, :] > 0)

True

### np.where（三元运算符）

In [49]:
# 判断前四个股票前四天的涨跌幅 大于0的置为1， 否则为0
temp = stock_change[:4, :4]

In [50]:
temp

array([[ 0.26625673,  0.22626729,  0.33018776, -0.77039285],
       [ 1.1       ,  1.1       ,  1.1       ,  0.2987972 ],
       [-0.73858731, -0.55980198, -0.58424396, -0.81942324],
       [ 0.03093299, -1.57553085, -1.24742813,  1.1       ]])

In [55]:
np.where(temp > 0, 1, 0)    # 判断temp>0的情况下，如果True 输出1，否则为0

array([[1, 1, 1, 0],
       [1, 1, 1, 1],
       [0, 0, 0, 0],
       [1, 0, 0, 1]])

In [56]:
# 可以用以下步骤实现同样的显示结果
temp >0

array([[ True,  True,  True, False],
       [ True,  True,  True,  True],
       [False, False, False, False],
       [ True, False, False,  True]])

In [57]:
np.where([[ True,  True,  True, False],
       [ True,  True,  True,  True],
       [False, False, False, False],
       [ True, False, False,  True]], 1, 0)

# 得出结果

array([[1, 1, 1, 0],
       [1, 1, 1, 1],
       [0, 0, 0, 0],
       [1, 0, 0, 1]])

In [58]:
# 复合逻辑判断
# 判断前四个股票前四天的涨跌幅 大于0.5并且小于1的 输出1，否则为0
# 判断前四个股票前四天的涨跌幅 大于0.5或者小于-0.5的 输出1，否则为0
np.logical_and(temp > 0.5, temp < 1) 

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [61]:
np.where([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]], 1, 0)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [67]:
np.where(np.logical_and(temp > 0.5, temp < 1), 1, 0) 
# 简化的写法

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [70]:
np.logical_or(temp > 0.5, temp < -0.5) 

array([[False, False, False,  True],
       [ True,  True,  True, False],
       [ True,  True,  True,  True],
       [False,  True,  True,  True]])

In [72]:
np.where(np.logical_or(temp > 0.5, temp < -0.5), 1, 0) 

array([[0, 0, 0, 1],
       [1, 1, 1, 0],
       [1, 1, 1, 1],
       [0, 1, 1, 1]])

In [78]:
# 股票涨跌幅统计运算
temp

array([[ 0.26625673,  0.22626729,  0.33018776, -0.77039285],
       [ 1.1       ,  1.1       ,  1.1       ,  0.2987972 ],
       [-0.73858731, -0.55980198, -0.58424396, -0.81942324],
       [ 0.03093299, -1.57553085, -1.24742813,  1.1       ]])

In [95]:
temp.max(axis=1)    # axies的理解 https://blog.csdn.net/sky_kkk/article/details/79725646

array([ 0.33018776,  1.1       , -0.55980198,  1.1       ])

In [91]:
np.max(temp, axis=-1)

array([ 0.33018776,  1.1       , -0.55980198,  1.1       ])

In [92]:
np.argmax(temp, axis=1)    # 标出列表中元素的下表

array([2, 0, 1, 3], dtype=int64)

In [100]:
# axis=0对应着最外层的[]，axis=1对应第二外层的[]，以此类推，axis=n对应第n外层的[]。
# axis=-n,-n+1,...,-3,-2,-1都是可以的。0,1,2,3,...
# 是从外开始剥，-n,-n+1,...,-3,-2,-1是从里开始剥。大家可以用下面的代码理解一下。
import numpy as np
a=np.array([[[1,2],[3,4]],[[11,12],[13,14]]])
print(a.sum(axis = 0))
 
b=np.array([[[1,2],[3,4]],[[11,12],[13,14]]])
print(b.sum(axis = -3))
 
c=np.array([[[1,2],[3,4]],[[11,12],[13,14]]])
print(c.sum(axis = 1))
 
d=np.array([[[1,2],[3,4]],[[11,12],[13,14]]])
print(d.sum(axis = -2))
 
e=np.array([[[1,2],[3,4]],[[11,12],[13,14]]])
print(e.sum(axis = 2))
 
f=np.array([[[1,2],[3,4]],[[11,12],[13,14]]])
print(f.sum(axis = -1))

[[12 14]
 [16 18]]
[[12 14]
 [16 18]]
[[ 4  6]
 [24 26]]
[[ 4  6]
 [24 26]]
[[ 3  7]
 [23 27]]
[[ 3  7]
 [23 27]]


### 数组与数的运算

In [4]:
import numpy as np
arr = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])

In [5]:
arr

array([[1, 2, 3, 2, 1, 4],
       [5, 6, 1, 2, 3, 1]])

In [6]:
arr1 = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])
arr2 = np.array([[1, 2, 3, 4],[3, 4, 5, 6]])
# arr1 + arr2 会出错，因为它们行，列不同
# 视频里后面讲的是多维数组之间相加或者相乘
# https://www.cnblogs.com/jiaxin359/p/9021726.html 这篇博客写得浅显易懂

### 矩阵乘法运算

In [19]:
import numpy as np
# 形状改变：（M行，N列）x（N行，L列）=（M行，L列）
# 矩阵乘法api

a = np.array([[80, 86],    #a.shape = (8,2)
[82, 80],
[85, 78],
[90, 90],
[86, 82],
[82, 90],
[78, 80],
[92, 94]])

# matrix存储矩阵
a_mat = np.mat([[80, 86],    #a.shape = (8,2)
[82, 80],
[85, 78],
[90, 90],
[86, 82],
[82, 90],
[78, 80],
[92, 94]])

b = np.array([[0.3], [0.7]])    #b.shape = (2,1)

b_mat = np.mat([[0.3], [0.7]])


In [20]:
b_mat

matrix([[0.3],
        [0.7]])

In [21]:
''' 
np.dot与np.matmul的区别
1.二者都是矩阵乘法。
2.np.matmul中禁止矩阵与标量的乘法。
3.在矢量乘矢量的內积运算中，np.matmul与np.dot没有区别。
4.np.matmul中，多维的矩阵，将前n-2维视为后2维的元素后，进行乘法运算。
'''

' \nnp.dot与np.matmul的区别\n1.二者都是矩阵乘法。\n2.np.matmul中禁止矩阵与标量的乘法。\n3.在矢量乘矢量的內积运算中，np.matmul与np.dot没有区别。\n4.np.matmul中，多维的矩阵，将前n-2维视为后2维的元素后，进行乘法运算。\n'

In [22]:
np.matmul(a, b)

array([[84.2],
       [80.6],
       [80.1],
       [90. ],
       [83.2],
       [87.6],
       [79.4],
       [93.4]])

In [23]:
np.matmul(a_mat, b_mat)    # 矩阵相乘

matrix([[84.2],
        [80.6],
        [80.1],
        [90. ],
        [83.2],
        [87.6],
        [79.4],
        [93.4]])

In [24]:
np.dot(a_mat, b_mat)    

matrix([[84.2],
        [80.6],
        [80.1],
        [90. ],
        [83.2],
        [87.6],
        [79.4],
        [93.4]])

In [25]:
a_mat * b_mat

matrix([[84.2],
        [80.6],
        [80.1],
        [90. ],
        [83.2],
        [87.6],
        [79.4],
        [93.4]])

In [26]:
a @ b

array([[84.2],
       [80.6],
       [80.1],
       [90. ],
       [83.2],
       [87.6],
       [79.4],
       [93.4]])